spring:
  profiles:
    active: mysql
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring-batch?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql=true:server.port: 8081

# job.name 값이 NONE 이면, 어떤 배치도 실행하지 않겠다. 는 뜻
spring.batch.job.names: ${job.name:NONE}

spring.jpa:
  generate-ddl: true
  hibernate.ddl-auto: update
  show-sql: true
  properties.hibernate.format_sql: true



# mail sender
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: iann20124test@gmail.com
  password: test1234!N
  properties.mail.smtp:
    auth: true
    starttls.enable: true

